const staffEndpoints = {
    login: "/login/staff",
    getClasses: "/staff/class/list-for-attendance",
    getAttendanceByClass: "/staff/attendance/class",
    getStudentsByClass: "/staff/class/students",
    postAttendance: "/staff/attendance",
    getTimeTable: "/public/tt/byClass",
    getStudentsDetails: "/school/student",
    getStaffAttendance: "/staff/myAttendance/monthly",
    Announcements: "/staff/announcement",
    getSubjectsOfStaff: "/staff/subjects/my-subjects",
    getStudentAttendance: "/staff/attendance/student",
    getSections: "/school/sections",
    getClassesGeneral: "/staff/class/list",
    createUnitTest: "/staff/exam/unitExam",
    getAllUnitTests: "/staff/exam/unitExam",
    updateUnitTest: "/staff/exam/unitExam/update",
    deleteUnitTest: "/staff/exam/unitExam/delete/permanently",
    cancelUnitTest: "/staff/exam/unitExam/cancel",
    completeUnitTest: "/staff/exam/unitExam/completed",
    postponeUnitTest: "/staff/exam/unitExam/postponed/indefinitely",
    getTeacherHomework: "/staff/homework/teacher",
    manageHomework: "/staff/homework",
    getProfileInfo: "/staff/profile",
    updateProfilePic: "/staff/profile-pic",
    getMyClasses: "/staff/class/list",

    getAllClasses: "/public/classSimpleList",
    getAllStandards: "/public/standardSimpleList",
    getAllGroups: "/public/groupsSimpleList",
    getAllMediums: "/public/mediumSimpleList",
    getAllSections: "/public/sectionsWithCode",
    unitTestMark: "/staff/exam/unitExam/mark",
    getUnitTestMark: "/staff/exam/unitExam/mark",
    publishUnitTestMark: "/staff/exam/unitExam/status/publish",

    //term exam
    getTermExams: "/staff/term/exam",
    getSubjects: "/staff/subjects/class",
    getTermExamMarksForClassTeacher: "/staff/term/exam/mark/class",
    getClasswiseTermExamMark: "/staff/term/exam/mark/class-wise-subject-marks",
    postTermExamMark: "/staff/term/exam/mark",
    publishTermExamtMark: "/staff/term/exam/mark/status",

    allStudentsInSchool: "/school/student",
    allStaffsInSchool: "/school/staff",

    getStaffAttendaceForSchoolHead: "/school-head/staff-attendance/by-date",
    updateStaffsAttendance: "/school-head/staff-attendance",
};

export default staffEndpoints;
