# command: docker-compose pull infuzio; docker-compose up   
services:
  postgres:
    image: postgres
    container_name: postgres-beta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: infuzio
    ports:
      - "5432:5432"
    volumes:
      - infuzio_psql_beta:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 3

  infuzio-beta:
    # build:
    #   context: .
    #   dockerfile: dockerfile
    platform: linux/amd64
    image: ghcr.io/infuzio-education/infuzio-backend-test:latest
    container_name: infuzio-beta
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: infuzio
      DB_PORT: 5432
      SUPER_ADMIN_USERNAME: superadmin
      SUPER_ADMIN_PASSWORD: adminpwsuper
      JWT_SECRET_KEY: djfsdhfsdkfhjdshfkdshfh
      DOCKER_ENV: true
    depends_on:
      postgres:
        condition: service_healthy  # Wait for PostgreSQL to be healthy
    # restart: on-failure  # Restart the infuzio container on failure


volumes:
  infuzio_psql_beta:
    name: "infuzio_psql_beta"
